### ISSUE TITLE
ccvr代码

### ISSUE THREAD

**Issue by Eddie-hy** [harrylee999/CRFDC#1]
您好，关于您的ccvr的对比代码，方便的话可以提供一下吗，万分感激，我的邮箱是15579102937@163.com

**Comment by harrylee999** [comment]
您好，我已经在仓库添加了CCVR的代码。
你可以直接使用
`python main.py -algo CCVR`

**Comment by harrylee999** [comment]
> 您好，关于您的ccvr的对比代码，方便的话可以提供一下吗，万分感激，我的邮箱是[15579102937@163.com](mailto:15579102937@163.com)

您好，我已经在仓库添加了CCVR的代码。
你可以直接使用
`python main.py -algo CCVR`
